---
version: "3.8"
services:
  app:
    build: .
    container_name: laravel_scaffold
    ports:
      - "8000:80"
    env_file:
      - .env
    volumes:
      - .:/var/www/html:rw
    networks:
      - app_network

  redis:
    image: 'redis:alpine'
    ports:
        - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
        - cache_data:/data
    networks:
        - app_network
    healthcheck:
        test:
            - CMD
            - redis-cli
            - ping
        retries: 3
        timeout: 5s

volumes:
  db_data:
    driver: "local"
  cache_data:
    driver: "local"

networks:
  app_network:
    driver: "bridge"